orphan:
	gcc -c -o main_orphan.o main_orphan.c -I .
	gcc -o exam main_orphan.o -I .
	rm -rf *.o
zombie:
	gcc -c -o main_zombie.o main_zombie.c -I .
	gcc -o exam main_zombie.o -I .
	rm -rf *.o
clean:
	rm -rf *.o test exam